In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('df_Clean_TripAdvisor 2023-09-05 14_24_13.csv')
df

,Unnamed: 0,Nombre,Score,Excelente,MuyBueno,Normal,Malo,Pesimo,Num_Reviews,Posicion,...,America Sur,Italiana,Española,Eur Occidental,Asador,N/A,India,Num_Reviews_Spain,Latitud,Longitud
0,0,El Capote,3.5,8,10,4,3,6,35,3525.0,...,0,0,1,0,0,0,0,31,40.420736,-3.684830
1,1,La Queda,4.5,8,3,0,0,0,13,1734.0,...,0,0,1,0,0,0,0,11,40.395330,-3.710880
2,2,Limbo Tribunal,4.0,86,57,11,12,8,191,41.0,...,0,0,0,0,1,0,0,174,40.425231,-3.700218
3,3,400 Grados Pizza - Maria de Molina,5.0,20,1,1,0,0,25,196.0,...,0,1,0,0,0,1,0,22,40.437473,-3.678595
4,4,Ginos,3.5,15,11,11,9,8,66,2166.0,...,0,1,1,0,0,1,0,54,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9407,9407,Salutteria Luchana,4.0,0,1,0,0,0,1,499.0,...,0,1,0,0,0,1,0,1,40.429436,-3.699675
9408,9408,Cafetería Los Arcos,2.5,4,6,7,12,23,109,5012.0,...,0,0,1,1,0,0,0,52,40.415006,-3.706646
9409,9409,Restaurante Pipa Don Ramon,3.5,5,1,2,1,2,11,1091.0,...,0,0,1,1,0,1,0,11,40.428694,-3.676716
9410,9410,El Rincon Murciano,4.0,29,25,5,1,3,64,1377.0,...,0,0,1,0,0,1,0,63,NaN,NaN
9411,9411,L'Abbraccio,4.0,132,108,30,8,4,303,479.0,...,0,1,1,0,0,0,0,282,40.463267,-3.692619